# This is a basic workflow to help you get started with Actions

name: test-work

# Controls when the workflow will run
on:
  push:
    branches: ["main"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [8.x, 10.x, 14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build a node environment using ${{ matrix.node_version }}
        run: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
